// ==UserScript==
// @name        Shimmer
// @description	A NightMode for Skimur!
// @author      Amy
// @include     http://skimur.com/*
// @include     https://skimur.com/*
// @include     http://*.skimur.com/*
// @include     https://*.skimur.com/*
// @run-at      document-start
// @version     1.0.1
// ==/UserScript==
(function() {var css = [
	"/*",
	"SHIMMER VERSION v1.0.1",
	"OPEN SOURCE PROJECT UNDER CC BY-SA LICENSE",
	"DESIGNED BY /U/AMY",
	"*/",
	"  ",
	"a:hover {",
	"    color: white !important;",
	"}",
	"div.row {",
	"	background: #292929 !important;",
	"	color: #ccc;",
	"}",
	"li.active {",
	"	background-color: #292929 !important;",
	"}",
	".layout-topbar {",
	"	background: #292929 !important;",
	"}",
	"a.topbar-edit:hover {",
	"	color: darkorange !important;",
	"	border-color: black !important;",
	"}",
	"a.topbar-edit {",
	"	background: #292929!important;",
	"        border-color: black !important;",
	"}",
	".layout-header {",
	"	background: #333333 !important;",
	"    border-color: black !important;",
	"}",
	".nav-tabs {",
	"	border-color: black !important;",
	"}",
	".nav-tabs > li > a:hover {",
	"	background: transparent !important;",
	"	border: none !important;",
	"	color: darkorange !important;",
	"}",
	".nav-tabs > li > a {",
	"	background: transparent !important;",
	"	border: none !important;",
	"	color: white !important;",
	"}",
	".nav-tabs > li {",
	"	margin-bottom: 0px !important;",
	"}",
	".btn.dropdown-toggle {",
	"	background: #333333;",
	"	color:white;",
	"}",
	".dropdown-menu a:hover {",
	"	color: darkorange !important;",
	"	background: none !important;",
	"}",
	".dropdown-menu {",
	"	background: #333333 !important;",
	"}",
	".dropdown-menu a {",
	"	color: white !important;",
	"}",
	".dropdown-toggle:hover {",
	"	background: #292929 !important;",
	"	color: white !important;",
	"}",
	".dropdown-toggle:focus {",
	"	background: #292929 !important;",
	"	color: white !important;",
	"}",
	".dropdown-toggle {",
	"	border-color: black !important;",
	"}",
	"body {",
	"    background: #292929 !important;",
	"}",
	".body-content  {",
	"	background-color: #292929 !important;",
	"}",
	"a.domain {",
	"	color: #aaa !important;",
	"}",
	".panel {",
	"	background: #292929 !important;",
	"}",
	".panel-heading {",
	"	background: #292929 !important;",
	"	border-color: black !important;",
	"	color: white !important;",
	"}",
	".panel-info {",
	"	border-color: black !important;",
	"}",
	".panel-search-info {",
	"	margin-top: 5px !important;",
	"	background: #333333 !important;",
	"	color: #c3c3c3 !important;",
	"	border-color: black !important;",
	"}",
	".sub-info {",
	"	margin-bottom: 8px;",
	"}",
	"ul.account-nav a:hover {",
	"	color: darkorange !important;",
	"}",
	"ul.account-nav  {",
	"	background: #333333 !important;",
	"	border: #333333 !important;",
	"}",
	"  ul.account-nav .divider {",
	"	border-color: #808080 !important;",
	"}",
	"blockquote {",
	"	border-color: #aaa !important",
	"}",
	".reports-unignored {",
	"	border-color: black !important;",
	"}",
	".list-group-item {",
	"	background: #292929 !important;",
	"    border-color: black !important;",
	"}",
	".btn-sm {",
	"	background: #333333 !important;",
	"	color: white !important;",
	"}",
	".btn-sm:hover {",
	"	color: darkorange !important;",
	"}",
	".md-input {",
	"	background: #333333 !important;",
	"}",
	".md-editor{",
	"	border-color: black !important;",
	"	border: none !important;",
	"	background: #292929 !important;",
	"}",
	".md-input {",
	"	border: none !important;",
	"	border-top: none solid black !important;",
	"	margin-top: 5px !important;",
	"}",
	".md-header.btn-toolbar {",
	"	background: #333333 !important;",
	"}",
	".md-editor.active {",
	"	box-shadow: none !important;",
	"}",
	".form-control, .input-group-addon {",
	"	background: #333333 !important;",
	"	border-color: black !important;",
	"}",
	".form-control {",
	"	box-shadow: none !important;",
	"	color: white !important;",
	"}",
	".message.message-unread {",
	"	background:#333333 !important;",
	"}",
	".disc .disc-body .disc-main .disc-options>li a {",
	"	color:#959595;",
	"	font-weight:700",
	"}",
	".disc .disc-body .disc-main:hover .disc-options>li a {",
	"	color:#ccc !important;",
	"}",
	".disc-main a.btn-default {",
	"	background: #B71C1C !important;",
	"	border-color: #B71C1C !important;",
	"	color: white !important",
	"}",
	".disc-main a.btn-default:hover {",
	"	background: #9C1717 !important;",
	"	border-color: #9C1717 !important",
	"}",
	".md-header.btn-toolbar {",
	"	background: #292929!important;",
	"}",
	".btn-default.btn-sm.btn {",
	"	border: none;",
	"	background: #292929 !important;",
	"}",
	".md-header .btn-primary {",
	"	border: none !important;",
	"}",
	".dropdown-menu-right a, .dropdown-menu-right a:hover{",
	"	background: #333333 !important;",
	"}",
	"::-moz-selection {",
	"	color: darkorange !important;",
	"}",
	".page-header.comments-header, .footer {",
	"	border-color: black !important;",
	"}",
	".btn-default.btn-lg, .unsubscribed {",
	"	background: #337ab7 !important;",
	"	border-color: #337ab7 !important;",
	"	color: white !important;",
	"}",
	".btn-default.btn-lg:hover, .unsubscribed:hover {",
	"	background: #286090 !important;",
	"	border-color: #286090 !important;",
	"}",
	".modal-body {",
	"	background: #333333",
	"}",
	".col-sm-6 .form-control {",
	"	color: white !important;",
	"}",
	"/*.fa-key {",
	"	color: #a94442 !important;",
	"} */",
	".modal-body div.row {",
	"	background: #333333 !important;",
	"	color: #ccc;",
	"}",
	".close.pull-right {",
	"	color: white !important;",
	"}",
	".sub-description {",
	"	background: #333333 !important;",
	"	border-color: black !important;",
	"}",
	".col-md-3 a:hover {",
	"	background: none !important;",
	"	color: darkorange !important;",
	"}"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node); 
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
